"""Offline builder for the G1 collision sidecar (spec sections 3-5).

Two modes:
    build  (default): read the AUTHORED collision_sidecar/g1_proxy_model.yaml (the human-edited
                      source of truth), derive the pair policy from the URDF tree, and emit
                      generated/g1_collision_sidecar.json (topology + hashes, CPU/CUDA input).
    --seed:           (re)generate the YAML by fitting tight capsules/spheres to the URDF's own
                      collision geometry. Run ONCE to bootstrap; manual tuning then lives in the
                      YAML and `build` (no --seed) preserves it.

The proxy model is a compact union of spheres and capsules (tens of primitives), NOT the
598-sphere GRiD representation.

Pair policy (spec section 4): auto-disable ONLY same-link, direct parent-child, and
fixed-relative-transform (same rigid group) pairs -- each with a recorded reason. Nested pairs
are NOT blanket-disabled; they are resolved by tightening/splitting proxies in the YAML.

    HJCD-IK/.venv/bin/python collision_sidecar/build_collision_sidecar.py [--seed]
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
import xml.etree.ElementTree as ET

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from urdf_model import parse_urdf, HJCD_JOINT_ORDER, _rpy_to_mat  # noqa: E402

URDF = os.path.join(REPO, "csrc", "urdf", "g1_29dof_rev_1_0.urdf")
YAML_OUT = os.path.join(HERE, "g1_proxy_model.yaml")
JSON_OUT = os.path.join(REPO, "generated", "g1_collision_sidecar.json")

RADIUS_FRAC = 0.72
MIN_RADIUS = 0.012
ASPECT_CAPSULE = 1.6
FIT_PERCENTILE = 55
# Rigid-cluster SDF narrow phase: a pair with one side in a cluster link is routed to that
# cluster's SDF (pair-generic; no hardcoded per-cluster algorithm).
CLUSTER_LINKS = {"torso_link": ("TORSO", "g1_torso_sdf.npz"),
                 "base_link": ("PELVIS", "g1_pelvis_sdf.npz")}
TORSO_LINK = "torso_link"       # (kept for back-compat references)

# Checkpoint 1D: the exact leg-region pairs where a limb CAPSULE is the proven limitation get
# an exact convex/GJK narrow phase (overrides the cluster/primitive routing for these pairs).
_WRISTS = ["left_wrist_yaw_link", "right_wrist_yaw_link"]
_THIGHS = [f"{s}_{seg}_link" for s in ("left", "right") for seg in ("hip_pitch", "hip_roll", "hip_yaw")]
GJK_PAIRS = {frozenset(("base_link", f"{s}_hip_roll_link")) for s in ("left", "right")}
GJK_PAIRS |= {frozenset((w, t)) for w in _WRISTS for t in _THIGHS}
# Checkpoint 3C.1: route ONLY the two shoulder_yaw<->torso pairs to exact convex/GJK (the torso-SDF
# proxy missed 5-10 mm penetrations here). torso stays a cluster SDF for every other limb pair.
GJK_PAIRS |= {frozenset((f"{s}_shoulder_yaw_link", "torso_link")) for s in ("left", "right")}
# Checkpoint 3C.2: the EXACT cross-body leg-leg pair classes with held-out deep FN (thin capsules
# missed 5-39 mm crossings). Confirmed from saved MuJoCo geom/link data -- NOT all leg-leg combos.
GJK_PAIRS |= {
    frozenset(("left_knee_link", "right_knee_link")),
    frozenset(("left_hip_yaw_link", "right_hip_yaw_link")),
    frozenset(("left_knee_link", "right_hip_yaw_link")),
    frozenset(("left_hip_yaw_link", "right_knee_link")),
}
# Checkpoint 3C.3: the two elbow<->torso pairs. Evidence, not symmetry alone: mining every deep
# MuJoCo false negative out of hard-mode outputs produced 21 records on right_elbow<->torso (up to
# 12.81 mm, all on the cluster-SDF phase), and mirroring those configurations left/right reproduced
# the collision 21/21 with the native model still missing 18 -- so the blind spot is symmetric and
# BOTH sides are routed. Exactly as in 3C.1, the torso stays a cluster SDF for every other pair.
GJK_PAIRS |= {frozenset((f"{s}_elbow_link", "torso_link")) for s in ("left", "right")}
# Native-completion checkpoint (Stage A): the 29 mirror-closed deep-FN pair classes from the broad
# production+diversified audit (g1_selfcoll_fn_corpus.json), every one a genuine model gap where a
# primitive/cluster-SDF proxy is pierced by MuJoCo (up to 19.6 mm). Read from data, not names:
# generated by mirror-closing the audit's `pair_classes`. `base_link<->torso_link` is included even
# though it was previously DISABLED as "cluster<->cluster, MuJoCo never collides" -- the audit
# refutes that assumption under extreme waist flexion, so it is un-disabled below and routed here.
# Native-completion §12: the carried-forward left_knee<->left_shoulder_yaw deep FN (and mirror).
# Both links already have convex geometry, so this is the small existing-typed-path fix the spec
# permits -- not a new routing campaign.
GJK_PAIRS |= {frozenset((f"{s}_knee_link", f"{s}_shoulder_yaw_link")) for s in ("left", "right")}
GJK_PAIRS |= {
    frozenset(("base_link", "torso_link")),
    # Task A foot closure: the 4 ankle_roll (foot, 4-sphere) cross-body pairs, now that typed GJK
    # supports sphere pieces. These were the documented residual of the previous checkpoint.
    frozenset(("left_ankle_roll_link", "right_hip_yaw_link")),
    frozenset(("left_ankle_roll_link", "right_knee_link")),
    frozenset(("left_hip_yaw_link", "right_ankle_roll_link")),
    frozenset(("left_knee_link", "right_ankle_roll_link")),
    frozenset(("left_elbow_link", "left_hip_roll_link")),
    frozenset(("left_elbow_link", "left_hip_yaw_link")),
    frozenset(("left_elbow_link", "left_knee_link")),
    frozenset(("left_hip_roll_link", "left_shoulder_yaw_link")),
    frozenset(("left_hip_roll_link", "left_wrist_pitch_link")),
    frozenset(("left_hip_roll_link", "torso_link")),
    frozenset(("left_hip_yaw_link", "left_shoulder_yaw_link")),
    frozenset(("left_hip_yaw_link", "left_wrist_pitch_link")),
    frozenset(("left_hip_yaw_link", "left_wrist_roll_link")),
    frozenset(("left_hip_yaw_link", "torso_link")),
    frozenset(("left_knee_link", "left_wrist_pitch_link")),
    frozenset(("left_knee_link", "left_wrist_roll_link")),
    frozenset(("right_elbow_link", "right_hip_roll_link")),
    frozenset(("right_elbow_link", "right_hip_yaw_link")),
    frozenset(("right_elbow_link", "right_knee_link")),
    frozenset(("right_hip_roll_link", "right_shoulder_yaw_link")),
    frozenset(("right_hip_roll_link", "right_wrist_pitch_link")),
    frozenset(("right_hip_roll_link", "torso_link")),
    frozenset(("right_hip_yaw_link", "right_shoulder_yaw_link")),
    frozenset(("right_hip_yaw_link", "right_wrist_pitch_link")),
    frozenset(("right_hip_yaw_link", "right_wrist_roll_link")),
    frozenset(("right_hip_yaw_link", "torso_link")),
    frozenset(("right_knee_link", "right_wrist_pitch_link")),
    frozenset(("right_knee_link", "right_wrist_roll_link")),
}
# base_link<->torso_link is a cluster<->cluster pair the generator auto-disables; force it back into
# the checked set (routed to GJK above) because the audit shows it genuinely collides.
FORCE_CHECK_PAIRS = {frozenset(("base_link", "torso_link"))}

PROXY_LINKS = [
    "base_link", "torso_link", "logo_link",
    "left_hip_pitch_link", "left_hip_roll_link", "left_hip_yaw_link", "left_knee_link",
    "left_ankle_pitch_link", "left_ankle_roll_link",
    "right_hip_pitch_link", "right_hip_roll_link", "right_hip_yaw_link", "right_knee_link",
    "right_ankle_pitch_link", "right_ankle_roll_link",
    "left_shoulder_pitch_link", "left_shoulder_roll_link", "left_shoulder_yaw_link",
    "left_elbow_link", "left_wrist_roll_link", "left_wrist_pitch_link", "left_wrist_yaw_link",
    "right_shoulder_pitch_link", "right_shoulder_roll_link", "right_shoulder_yaw_link",
    "right_elbow_link", "right_wrist_roll_link", "right_wrist_pitch_link", "right_wrist_yaw_link",
]


# ---------------------------------------------------------------------------
# minimal YAML reader/writer for the fixed proxy-model schema (no yaml dep)
# ---------------------------------------------------------------------------
def load_proxies(path=YAML_OUT):
    """Parse g1_proxy_model.yaml -> (primitives, manual_disabled). Fixed schema this module
    writes: a `primitives:` list of `- name/link/type/(center|p0,p1)/radius` blocks, then an
    optional `manual_disabled:` list of `- [a, b]  # reason`."""
    prims, manual = [], []
    section, cur = None, None

    def flush():
        nonlocal cur
        if cur:
            prims.append(cur); cur = None
    for raw in open(path):
        s = raw.strip()
        if not s or s.startswith("#"):
            continue
        if s == "primitives:":
            section = "prim"; continue
        if s.startswith("manual_disabled:"):
            flush(); section = "man"; continue
        if section == "prim":
            if s.startswith("- name:"):
                flush(); cur = {"name": s.split(":", 1)[1].strip()}
            elif ":" in s and cur is not None:
                k, v = s.split(":", 1); k, v = k.strip(), v.strip()
                if v.startswith("["):
                    cur[k] = [float(x) for x in v.strip("[]").split(",")]
                else:
                    try:
                        cur[k] = float(v)
                    except ValueError:
                        cur[k] = v
        elif section == "man" and s.startswith("- ["):
            body = s[1:].strip()
            pair = body.split("#")[0].strip().strip("[]")
            reason = body.split("#", 1)[1].strip() if "#" in body else "manual"
            a, b = [x.strip() for x in pair.split(",")]
            manual.append(dict(a=a, b=b, reason=reason))
    flush()
    return prims, manual


def _fmt_prim(p):
    if p["type"] == "sphere":
        c = p["center"]
        return (f"  - name: {p['name']}\n    link: {p['link']}\n    type: sphere\n"
                f"    center: [{c[0]:.5f}, {c[1]:.5f}, {c[2]:.5f}]\n    radius: {p['radius']:.5f}")
    a, b = p["p0"], p["p1"]
    return (f"  - name: {p['name']}\n    link: {p['link']}\n    type: capsule\n"
            f"    p0: [{a[0]:.5f}, {a[1]:.5f}, {a[2]:.5f}]\n"
            f"    p1: [{b[0]:.5f}, {b[1]:.5f}, {b[2]:.5f}]\n    radius: {p['radius']:.5f}")


def write_yaml(primitives, header_notes=(), manual_disabled=()):
    lines = ["# G1 compact collision proxy model (spheres + capsules), link-local frames.",
             "# Source of truth for the sidecar; build_collision_sidecar.py (no --seed) reads THIS.",
             f"# primitive_count: {len(primitives)}"]
    lines += [f"# {n}" for n in header_notes]
    lines.append("primitives:")
    lines += [_fmt_prim(p) for p in primitives]
    if manual_disabled:
        lines.append("manual_disabled:")
        for a, b, reason in manual_disabled:
            lines.append(f"  - [{a}, {b}]  # {reason}")
    open(YAML_OUT, "w").write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# seed: fit proxies from URDF collision geometry
# ---------------------------------------------------------------------------
def _link_collision_points(root, link_name):
    import trimesh
    pts, prims = [], []
    for le in root.findall("link"):
        if le.get("name") != link_name:
            continue
        for ce in le.findall("collision"):
            oe = ce.find("origin")
            oxyz = np.array([float(v) for v in (oe.get("xyz", "0 0 0").split())]) if oe is not None else np.zeros(3)
            orpy = np.array([float(v) for v in (oe.get("rpy", "0 0 0").split())]) if oe is not None else np.zeros(3)
            R = _rpy_to_mat(orpy)
            g = ce.find("geometry")
            mesh, sph, cyl = g.find("mesh"), g.find("sphere"), g.find("cylinder")
            if mesh is not None:
                fn = mesh.get("filename")
                path = os.path.join(REPO, "csrc", "urdf", fn) if not os.path.isabs(fn) else fn
                if os.path.exists(path):
                    v = np.asarray(trimesh.load(path, force="mesh").vertices)
                    pts.append((R @ v.T).T + oxyz)
            elif sph is not None:
                prims.append(dict(type="sphere", center=oxyz.tolist(), radius=float(sph.get("radius"))))
            elif cyl is not None:
                r, h = float(cyl.get("radius")), float(cyl.get("length"))
                a = R @ np.array([0, 0, h / 2.0])
                prims.append(dict(type="capsule", p0=(oxyz - a).tolist(), p1=(oxyz + a).tolist(), radius=r))
    return (np.vstack(pts) if pts else np.zeros((0, 3))), prims


def _fit_proxy(points):
    c = points.mean(0)
    X = points - c
    _, _, Vt = np.linalg.svd(X, full_matrices=False)
    axis = Vt[0]
    t = X @ axis
    perp = np.linalg.norm(X - np.outer(t, axis), axis=1)
    radius = max(MIN_RADIUS, RADIUS_FRAC * float(np.percentile(perp, FIT_PERCENTILE)))
    length = float(t.max() - t.min())
    if length > ASPECT_CAPSULE * radius:
        return dict(type="capsule", p0=(c + axis * t.min()).tolist(),
                    p1=(c + axis * t.max()).tolist(), radius=radius)
    return dict(type="sphere", center=c.tolist(), radius=max(radius, 0.5 * length + MIN_RADIUS))


def seed_from_meshes():
    model = parse_urdf(URDF)
    root = ET.parse(URDF).getroot()
    primitives = []
    for link in PROXY_LINKS:
        if link not in model.links:
            continue
        P, prims = _link_collision_points(root, link)
        used = []
        for pr in prims:
            pr = dict(pr); pr["link"] = link; pr["name"] = f"{link}:{pr['type']}{len(used)}"
            used.append(pr)
        if not used and len(P) >= 4:
            pr = _fit_proxy(P); pr["link"] = link; pr["name"] = f"{link}:fit"
            used.append(pr)
        primitives.extend(used)
    write_yaml(primitives)
    print(f"seeded {len(primitives)} proxies -> {os.path.relpath(YAML_OUT, REPO)}")


# ---------------------------------------------------------------------------
# build: YAML -> pair policy + topology JSON
# ---------------------------------------------------------------------------
def build():
    model = parse_urdf(URDF)
    primitives, manual_disabled = load_proxies()

    parent_fixed = {}
    for j in model.joints:
        if not j.movable:
            parent_fixed.setdefault(j.child, j.parent)

    def rigid_root(l):
        seen = set()
        while l in parent_fixed and l not in seen:
            seen.add(l); l = parent_fixed[l]
        return l
    group = {l: rigid_root(l) for l in model.links}
    adj = {frozenset((j.parent, j.child)) for j in model.joints}
    # rigid-CLUSTER adjacency: two links are structurally adjacent if a member of one link's
    # rigid group is the parent/child of a member of the other's -- i.e. one link is bolted onto
    # the other's rigid cluster (e.g. hip_pitch onto the base_link/pelvis cluster). This is the
    # "direct parent-child" rule lifted to fixed clusters; it is NOT a per-pose overlap heuristic.
    cluster_adj = {frozenset((group[j.parent], group[j.child]))
                   for j in model.joints if group[j.parent] != group[j.child]}
    manual_set = {frozenset((d["a"], d["b"])): d["reason"] for d in manual_disabled}
    cluster_link_set = set(CLUSTER_LINKS)

    links_with_prims = sorted({p["link"] for p in primitives})
    disabled, checked_link_pairs = [], []
    for i in range(len(links_with_prims)):
        for k in range(i + 1, len(links_with_prims)):
            a, b = links_with_prims[i], links_with_prims[k]
            key = frozenset((a, b))
            if key in FORCE_CHECK_PAIRS and group[a] != group[b] and key not in adj:
                # Audit-driven override of a structural exclusion: a pair the generator would
                # auto-disable but the MuJoCo oracle shows genuinely collides. Only lifts the
                # cluster/heuristic exclusions, never the hard same-group / direct parent-child ones.
                checked_link_pairs.append([a, b])
            elif group[a] == group[b]:
                disabled.append(dict(a=a, b=b, reason="fixed_relative_transform (same rigid group)"))
            elif key in adj:
                disabled.append(dict(a=a, b=b, reason="direct parent-child"))
            elif frozenset((group[a], group[b])) in cluster_adj:
                disabled.append(dict(a=a, b=b, reason="rigid-cluster parent-child (link bolted onto the other's fixed cluster)"))
            elif a in cluster_link_set and b in cluster_link_set:
                disabled.append(dict(a=a, b=b, reason="cluster<->cluster (central bodies joined by the waist chain; MuJoCo never collides)"))
            elif key in manual_set:
                disabled.append(dict(a=a, b=b, reason="MANUAL: " + manual_set[key]))
            else:
                checked_link_pairs.append([a, b])

    link_prims = {}
    for idx, p in enumerate(primitives):
        link_prims.setdefault(p["link"], []).append(idx)

    def ptype(i):
        return primitives[i]["type"]
    # Hybrid pair policy (Checkpoint 1B/1C): a pair with one side in a rigid CLUSTER link uses
    # that cluster's SDF as the narrow phase (limb primitive vs the cluster-local SDF); the
    # cluster's compact capsule stays as the broad phase. All other pairs use sphere/capsule.
    prim_pairs = {"sphere_sphere": [], "sphere_capsule": [], "capsule_capsule": []}
    cluster_prims = {cid: [] for (cid, _f) in CLUSTER_LINKS.values()}      # cid -> limb prim idxs
    gjk_link_pairs = []
    for a, b in checked_link_pairs:
        if frozenset((a, b)) in GJK_PAIRS:
            gjk_link_pairs.append([a, b]); continue                       # exact convex narrow phase
        ca, cb = a in CLUSTER_LINKS, b in CLUSTER_LINKS
        if ca or cb:
            # cluster-cluster: query the (non-first) cluster's broad prim vs the first cluster's SDF
            cluster_link = a if ca else b
            limb = b if ca else a
            cid = CLUSTER_LINKS[cluster_link][0]
            cluster_prims[cid].extend(link_prims[limb])
            continue
        for ia in link_prims[a]:
            for ib in link_prims[b]:
                ta, tb = ptype(ia), ptype(ib)
                if ta == "sphere" and tb == "sphere":
                    prim_pairs["sphere_sphere"].append([ia, ib])
                elif ta == "capsule" and tb == "capsule":
                    prim_pairs["capsule_capsule"].append([ia, ib])
                else:
                    prim_pairs["sphere_capsule"].append([ia, ib] if ta == "sphere" else [ib, ia])
    clusters = {}
    for link, (cid, sdf_file) in CLUSTER_LINKS.items():
        if link not in link_prims:
            continue
        prims_l = sorted(set(cluster_prims[cid]))
        clusters[cid] = {"link": link, "sdf_file": sdf_file,
                         "limb_prims": prims_l,
                         "broad_prim": link_prims[link][0]}
    # back-compat fields (torso)
    torso_sphere_prims = [i for i in clusters.get("TORSO", {}).get("limb_prims", []) if ptype(i) == "sphere"]
    torso_capsule_prims = [i for i in clusters.get("TORSO", {}).get("limb_prims", []) if ptype(i) == "capsule"]

    joint_desc = {n: model.descendant_links(n) for n in HJCD_JOINT_ORDER}
    joint_pairs = {}
    for n in HJCD_JOINT_ORDER:
        sub = set(joint_desc[n])
        joint_pairs[n] = [i for i, (a, b) in enumerate(checked_link_pairs) if (a in sub) ^ (b in sub)]

    yaml_hash = hashlib.sha1(open(YAML_OUT, "rb").read()).hexdigest()[:16]
    art = {
        "urdf_hash": model.urdf_hash(), "joint_order_hash": model.joint_order_hash(),
        "proxy_yaml_hash": yaml_hash, "hjcd_joint_order": list(HJCD_JOINT_ORDER),
        "root_link": model.root_link, "primitives": primitives,
        "checked_link_pairs": checked_link_pairs, "disabled_pairs": disabled,
        "primitive_pairs": prim_pairs, "link_primitives": link_prims,
        "joint_descendant_links": joint_desc, "joint_affected_pairs": joint_pairs,
        "n_primitives": len(primitives), "n_checked_link_pairs": len(checked_link_pairs),
        "n_disabled_pairs": len(disabled),
        # hybrid narrow phase (Checkpoint 1B/1C)
        "torso_link": TORSO_LINK,
        "cluster_links": {k: v[0] for k, v in CLUSTER_LINKS.items()},
        "clusters": clusters,
        "torso_sphere_prims": torso_sphere_prims,
        "torso_capsule_prims": torso_capsule_prims,
        "n_cluster_sdf_pairs": sum(len(c["limb_prims"]) for c in clusters.values()),
        # convex/GJK narrow phase (Checkpoint 1D)
        "gjk_pairs": gjk_link_pairs,
        "convex_pieces_file": "g1_convex_pieces.json",
    }
    os.makedirs(os.path.dirname(JSON_OUT), exist_ok=True)
    json.dump(art, open(JSON_OUT, "w"), indent=1)
    print(f"proxies: {len(primitives)} ({sum(p['type']=='sphere' for p in primitives)} sph, "
          f"{sum(p['type']=='capsule' for p in primitives)} cap) | "
          f"checked link-pairs: {len(checked_link_pairs)}  disabled: {len(disabled)} "
          f"(manual: {len(manual_set)}) | prim-pairs ss={len(prim_pairs['sphere_sphere'])} "
          f"sc={len(prim_pairs['sphere_capsule'])} cc={len(prim_pairs['capsule_capsule'])}")
    return art


if __name__ == "__main__":
    if "--seed" in sys.argv:
        seed_from_meshes()
    build()
