"""Deterministic MuJoCo reference corpus for G1 self-collision (spec section 1 / 10).

MuJoCo is the oracle. For each configuration we store the config-level label AND the colliding
MuJoCo link pairs + penetration depths. Categories (spec):
    neutral, nominal crouch, known-free climbing stances, random in-limit, HJCD outputs,
    deliberate arm-torso / elbow-wrist / leg-leg / hand-body / hip-pelvis collisions, and
    near-contact configs around each of the three residual pairs.

Deliberate-collision categories are generated by sweeping the relevant joints toward contact
and KEEPING the configs MuJoCo confirms as colliding for the intended link pair. Deterministic
seeds; split into tuning / held-out.

Runs from the parent venv (needs MuJoCo). Writes generated/g1_collision_corpus.json.

    MUJOCO_GL=egl python3 collision_sidecar/corpus.py
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
HJCD = os.path.dirname(HERE)
PARENT = os.path.dirname(os.path.dirname(HJCD))     # robot_bouldering
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(PARENT, "src"))
sys.path.insert(0, os.path.join(PARENT, "production"))

import mujoco  # noqa: E402
from urdf_model import HJCD_JOINT_ORDER  # noqa: E402

OUT = os.path.join(HJCD, "generated", "g1_collision_corpus.json")


class MujocoOracle:
    """Canonical G1 self-collision labels (the same model/opts the planner trusts)."""

    def __init__(self):
        import route_qs_lsq as RQ
        self.inp = RQ.load_inputs()
        self.m, self.d = self.inp.model, self.inp.data
        self.self_opts = self.inp.self_opts
        self.qadr = {n: int(self.m.jnt_qposadr[mujoco.mj_name2id(self.m, mujoco.mjtObj.mjOBJ_JOINT, n)])
                     for n in HJCD_JOINT_ORDER}
        fj = [j for j in range(self.m.njnt) if self.m.jnt_type[j] == mujoco.mjtJoint.mjJNT_FREE][0]
        self.free_qw = int(self.m.jnt_qposadr[fj]) + 3
        self.lim = np.array([self.m.jnt_range[mujoco.mj_name2id(self.m, mujoco.mjtObj.mjOBJ_JOINT, n)]
                             for n in HJCD_JOINT_ORDER])

    def set_q(self, q):
        self.d.qpos[:] = 0.0
        self.d.qpos[self.free_qw] = 1.0
        for n, v in zip(HJCD_JOINT_ORDER, q):
            self.d.qpos[self.qadr[n]] = v
        self.d.qvel[:] = 0.0
        mujoco.mj_forward(self.m, self.d)

    def label(self, q):
        from bouldering.collision import check_pose_collision
        self.set_q(q)
        res = check_pose_collision(self.m, self.d, self.d.qpos.copy(), options=self.self_opts)
        sc = [i for i in res.issues if i.kind == "self_collision"]
        pairs = sorted({(tuple(sorted((str(i.body1), str(i.body2)))), round(float(i.penetration) * 1000, 2))
                        for i in sc})
        return {"colliding": bool(sc),
                "pairs": [[list(p), d] for p, d in pairs]}


def _clip(oracle, q):
    return np.clip(q, oracle.lim[:, 0] + 1e-4, oracle.lim[:, 1] - 1e-4)


def build_corpus(n_random=120, n_hjcd=40, n_deliberate=30, seed=7):
    o = MujocoOracle()
    J = {n: i for i, n in enumerate(HJCD_JOINT_ORDER)}
    rng = np.random.default_rng(seed)
    samples = []   # each: dict(category, q, label)

    def add(cat, q, split):
        q = _clip(o, np.asarray(q, float))
        samples.append(dict(category=cat, split=split, q=q.tolist(), label=o.label(q)))

    # --- fixed reference poses -------------------------------------------
    add("neutral", np.zeros(29), "tuning")
    crouch = np.zeros(29)
    for side in ("left", "right"):
        crouch[J[f"{side}_hip_pitch_joint"]] = -0.7
        crouch[J[f"{side}_knee_joint"]] = 1.2
        crouch[J[f"{side}_ankle_pitch_joint"]] = -0.5
        crouch[J[f"{side}_shoulder_pitch_joint"]] = 0.3
    add("crouch", crouch, "tuning")

    # --- known climbing stances + HJCD outputs (MuJoCo labels them) ------
    try:
        art = json.load(open(os.path.join(PARENT, "production", "prod_outputs", "route_refined.json")))
        for st in art["stances"]:
            q36 = np.asarray(st["qpos"], float)
            q = np.array([q36[o.qadr[n]] for n in HJCD_JOINT_ORDER])
            add("climbing_stance", q, "tuning" if st["stance_index"] % 2 == 0 else "heldout")
    except Exception as e:
        print("  [warn] stances unavailable:", e)
    try:
        rep = json.load(open(os.path.join(PARENT, "production", "prod_outputs", "ik_batch_report.json")))
        feas = [r for r in rep["results"] if r.get("best_qpos")][:n_hjcd]
        for k, r in enumerate(feas):
            q36 = np.asarray(r["best_qpos"], float)
            q = np.array([q36[o.qadr[n]] for n in HJCD_JOINT_ORDER])
            add("hjcd_output", q, "tuning" if k % 2 == 0 else "heldout")
    except Exception as e:
        print("  [warn] HJCD outputs unavailable:", e)

    # --- random in-limit --------------------------------------------------
    for k in range(n_random):
        q = rng.uniform(o.lim[:, 0], o.lim[:, 1])
        add("random", q, "tuning" if k % 2 == 0 else "heldout")

    # --- deliberate collisions: grid-sweep joints toward contact, keep the configs MuJoCo
    #     confirms colliding FOR THE TARGET link region (keyword match on the colliding pair).
    def pair_hits(lab, want_a, want_b):
        for (pair, _dep) in lab["pairs"]:
            names = " ".join(pair)
            if any(a in names for a in want_a) and any(b in names for b in want_b):
                return True
        return False

    def grid_sweep(cat, configs, want_a, want_b, cap=n_deliberate):
        got = 0
        for q in configs:
            if got >= cap:
                break
            lab = o.label(_clip(o, q))
            if lab["colliding"] and pair_hits(lab, want_a, want_b):
                add(cat, q, "tuning" if got % 2 == 0 else "heldout")
                got += 1
        return got

    def arm_torso_configs():
        for roll in np.linspace(-1.6, 1.6, 12):
            for pitch in (0.0, 0.5, 1.0, 1.5):
                for elbow in (0.0, 1.5):
                    q = np.zeros(29)
                    q[J["left_shoulder_roll_joint"]] = roll
                    q[J["left_shoulder_pitch_joint"]] = pitch
                    q[J["left_elbow_joint"]] = elbow
                    yield q

    def hand_body_configs():
        for pitch in np.linspace(0.2, 1.6, 6):
            for roll in np.linspace(-1.4, 0.2, 6):        # adduct across the chest
                for elbow in (1.6, 2.1):
                    q = np.zeros(29)
                    q[J["left_shoulder_pitch_joint"]] = pitch
                    q[J["left_shoulder_roll_joint"]] = roll
                    q[J["left_elbow_joint"]] = elbow
                    yield q

    def elbow_wrist_configs():        # fold the forearm/hand back onto the upper arm
        for elbow in np.linspace(1.6, 2.4, 5):
            for yaw in (-1.0, 0.0, 1.0):
                for wp in (-1.2, 0.0, 1.2):
                    q = np.zeros(29)
                    q[J["left_elbow_joint"]] = elbow
                    q[J["left_shoulder_yaw_joint"]] = yaw
                    q[J["left_wrist_pitch_joint"]] = wp
                    yield q

    def leg_leg_configs():
        for mag in np.linspace(0.05, 0.5, 20):
            q = np.zeros(29)
            q[J["left_hip_roll_joint"]] = -mag
            q[J["right_hip_roll_joint"]] = mag
            yield q

    def hip_pelvis_configs():
        for mag in np.linspace(1.3, 2.8, 20):
            for roll in (0.0, -0.4):
                q = np.zeros(29)
                q[J["left_hip_pitch_joint"]] = -mag
                q[J["left_hip_roll_joint"]] = roll
                yield q

    ARM = ["shoulder", "elbow"]
    HAND = ["wrist", "hand", "rubber"]
    for cat, cfgs, wa, wb in [
        ("deliberate_arm_torso", arm_torso_configs(), ARM, ["torso"]),
        # NB: the G1 forearm cannot self-collide onto the upper arm within joint limits; a
        # folded arm reaches the LOWER body -- the realizable forearm-region collision is
        # wrist/hand vs hip/base. (See the diagnostic note in the Checkpoint-1 report.)
        ("deliberate_forearm", elbow_wrist_configs(), HAND, ["hip", "base", "pelvis"]),
        ("deliberate_leg_leg", leg_leg_configs(), ["left_"], ["right_"]),
        ("deliberate_hand_body", hand_body_configs(), HAND, ["torso", "pelvis", "waist"]),
        ("deliberate_hip_pelvis", hip_pelvis_configs(), ["hip", "knee", "thigh"], ["pelvis", "waist", "torso"]),
    ]:
        n = grid_sweep(cat, cfgs, wa, wb)
        print(f"  {cat}: {n} MuJoCo-confirmed colliding for target region")

    # --- near-contact around the three residual pairs --------------------
    def near(cat, base_fn):
        for k in range(16):
            q = base_fn(rng.normal(scale=0.15, size=29))
            add(cat, q, "tuning" if k % 2 == 0 else "heldout")
    near("near_elbow_wrist", lambda pert: np.clip(pert, -0.3, 0.3))          # small around neutral arm
    near("near_shoulder_torso",
         lambda pert: (lambda q: (q.__setitem__(J["left_shoulder_roll_joint"], 0.3 + pert[0]), q)[1])(np.zeros(29)))

    # --- persist ----------------------------------------------------------
    tuning = [s for s in samples if s["split"] == "tuning"]
    heldout = [s for s in samples if s["split"] == "heldout"]
    n_coll = sum(s["label"]["colliding"] for s in samples)
    json.dump({"n": len(samples), "n_tuning": len(tuning), "n_heldout": len(heldout),
               "n_colliding": n_coll, "n_free": len(samples) - n_coll,
               "hjcd_joint_order": list(HJCD_JOINT_ORDER), "samples": samples},
              open(OUT, "w"))
    print(f"\ncorpus: {len(samples)} configs ({n_coll} colliding, {len(samples)-n_coll} free) "
          f"| tuning {len(tuning)}  heldout {len(heldout)}")
    print(f"wrote {os.path.relpath(OUT, HJCD)}")


if __name__ == "__main__":
    build_corpus()
